// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIKPZACaLHNF3NypHjgIScRwRhpuiOOk',
    appId: '1:1082350793346:web:a699905bf9db8778b03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    authDomain: 'club-f0ffa.firebaseapp.com',
    storageBucket: 'club-f0ffa.appspot.com',
    measurementId: 'G-MYKPRV83EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdk8LUM4zzTrys5V4YwXqniLgcGmy-bDA',
    appId: '1:1082350793346:android:986e1240a151eddcb03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    storageBucket: 'club-f0ffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5tZm5wTSpLSWRLqwtfiih1osfURUx49g',
    appId: '1:1082350793346:ios:9523626b573e7394b03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    storageBucket: 'club-f0ffa.appspot.com',
    iosBundleId: 'com.example.club',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5tZm5wTSpLSWRLqwtfiih1osfURUx49g',
    appId: '1:1082350793346:ios:9523626b573e7394b03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    storageBucket: 'club-f0ffa.appspot.com',
    iosBundleId: 'com.example.club',
  );
}
